<template>
  <div class="space-y-6">
    <div><h1 class="text-2xl font-bold tracking-tight text-slate-900">Absence Justifications</h1><p class="mt-1 text-xs text-slate-500">{{ role === 'administrator' ? 'Review student submissions and configure the fixed deadline.' : 'Submit your own absence justification before the administrator-configured deadline.' }}</p></div>
    <div v-if="errorMessage" class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700" role="alert">{{ errorMessage }}</div><div v-if="successMessage" class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700" role="status">{{ successMessage }}</div>
    <form v-if="role === 'administrator'" class="rounded-xl border border-blue-200 bg-blue-50/60 p-5 shadow-xs" @submit.prevent="savePolicy"><h2 class="text-base font-bold text-slate-900">Absence policy</h2><p class="mt-1 text-xs text-slate-600">Students receive this fixed number of days after an absence to submit a justification.</p><div class="mt-4 flex flex-wrap items-end gap-3"><label class="block text-xs font-semibold text-slate-700">Deadline days<input v-model.number="policyDays" type="number" min="1" max="30" required class="mt-1.5 block w-32 rounded-md border border-slate-200 bg-white px-3 py-2 text-sm" /></label><button type="submit" class="btn-primary px-4 py-2 text-xs font-semibold" :disabled="saving">Save deadline</button></div></form>
    <section class="rounded-xl border border-border-subtle bg-white p-4 shadow-xs sm:p-6"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-base font-bold text-slate-900">{{ role === 'administrator' ? 'Student submissions' : 'My absence records' }}</h2><p class="mt-1 text-xs text-slate-500">A rejected or expired justification becomes unjustified and can trigger guardian and discipline follow-up.</p></div><button type="button" class="btn-primary px-3 py-2 text-xs font-semibold" @click="loadData">Refresh</button></div><div v-if="loading" class="py-10 text-center text-sm text-slate-500">Loading absence records…</div><div v-else-if="!records.length" class="py-10 text-center text-sm text-slate-500">No absent records require action.</div><div v-else class="space-y-3"><article v-for="record in records" :key="record.attendance_id" class="rounded-lg border border-slate-200 bg-slate-50 p-4"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="font-bold text-slate-900">{{ role === 'administrator' ? record.student?.full_name : 'Absence' }} · {{ record.session_date }}</p><p class="mt-1 text-xs text-slate-500">Status: {{ record.justification_status }} · Deadline: {{ formatDate(record.justification_deadline_at) }}</p><p v-if="record.justification_text" class="mt-2 text-sm text-slate-700">{{ record.justification_text }}</p><p v-if="record.justification_review_note" class="mt-1 text-xs text-slate-500">Review note: {{ record.justification_review_note }}</p></div><span class="rounded-full bg-white px-2 py-1 text-[10px] font-semibold text-slate-600">{{ record.class_session?.course?.course_code || 'Course' }}</span></div><div v-if="role === 'student' && ['PENDING','SUBMITTED'].includes(record.justification_status)" class="mt-3 flex flex-col gap-2 sm:flex-row"><textarea v-model="drafts[record.attendance_id]" rows="2" maxlength="2000" class="min-w-0 flex-1 rounded-md border border-slate-200 bg-white px-3 py-2 text-sm" placeholder="Explain the reason for your absence."></textarea><button type="button" class="btn-primary px-3 py-2 text-xs font-semibold" @click="submit(record)">Submit justification</button></div><div v-if="role === 'administrator' && record.justification_status === 'SUBMITTED'" class="mt-3 flex gap-2"><button type="button" class="btn-primary px-3 py-2 text-xs font-semibold" @click="review(record, 'APPROVED')">Approve</button><button type="button" class="btn-danger px-3 py-2 text-xs font-semibold" @click="review(record, 'REJECTED')">Reject</button></div></article></div></section>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { authStore } from '../store/auth.js'
import { fetchAbsenceJustifications, fetchAbsencePolicy, reviewAbsenceJustification, submitAbsenceJustification, updateAbsencePolicy } from '../api.js'

const role = computed(() => authStore.userRole.value)
const records = ref([])
const drafts = reactive({})
const policyDays = ref(3)
const loading = ref(true)
const saving = ref(false)
const errorMessage = ref('')
const successMessage = ref('')
function formatDate(value) { return value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'Not set' }
async function loadData() { loading.value = true; errorMessage.value = ''; const result = await fetchAbsenceJustifications(authStore.token.value); if (!result.ok) errorMessage.value = result.error || 'Unable to load absence justifications.'; else records.value = result.data || []; if (role.value === 'administrator') { const policy = await fetchAbsencePolicy(authStore.token.value); if (policy.ok) policyDays.value = policy.data?.justification_deadline_days || 3 } loading.value = false }
async function savePolicy() { saving.value = true; const result = await updateAbsencePolicy(authStore.token.value, { justification_deadline_days: policyDays.value }); if (!result.ok) errorMessage.value = result.error || 'Unable to save the absence deadline.'; else successMessage.value = 'Absence justification deadline updated.'; saving.value = false }
async function submit(record) { const result = await submitAbsenceJustification(authStore.token.value, record.attendance_id, { justification_text: drafts[record.attendance_id] || '' }); if (!result.ok) errorMessage.value = result.error || 'Unable to submit justification.'; else { successMessage.value = 'Justification submitted for administrator review.'; await loadData() } }
async function review(record, status) { const note = window.prompt(`${status === 'APPROVED' ? 'Approval' : 'Rejection'} note (optional):`) || ''; const result = await reviewAbsenceJustification(authStore.token.value, record.attendance_id, { status, justification_review_note: note }); if (!result.ok) errorMessage.value = result.error || 'Unable to review justification.'; else { successMessage.value = `Justification ${status.toLowerCase()}.`; await loadData() } }
onMounted(loadData)
</script>
