<template>
  <section class="space-y-6">
    <header class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
      <div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-600">Administration</p><h1 class="mt-1 text-2xl font-bold text-slate-950">Grading review & publication</h1><p class="mt-1 max-w-3xl text-sm text-slate-500">Review every mark submitted by teachers. Students and guardians only see assessment marks after you publish them.</p></div>
      <label class="text-sm font-medium text-slate-700">Term<input v-model="term" class="mt-1 block w-40 rounded-lg border border-slate-300 px-3 py-2 text-sm" placeholder="2026-A" @change="load" /></label>
    </header>
    <p v-if="message" class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ message }}</p>
    <p v-if="errorMessage" class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ errorMessage }}</p>

    <div class="grid grid-cols-2 gap-4 md:grid-cols-4"><div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs text-slate-500">Assessments</p><p class="mt-1 text-2xl font-bold text-slate-900">{{ assessments.length }}</p></div><div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs text-slate-500">Submitted marks</p><p class="mt-1 text-2xl font-bold text-slate-900">{{ records.length }}</p></div><div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs text-slate-500">Awaiting review</p><p class="mt-1 text-2xl font-bold text-amber-700">{{ awaitingReview }}</p></div><div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs text-slate-500">Published marks</p><p class="mt-1 text-2xl font-bold text-emerald-700">{{ publishedMarks }}</p></div></div>

    <div class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h2 class="font-bold text-slate-900">Assessment submissions</h2><p class="mt-1 text-xs text-slate-500">An assessment can be published only after the teacher confirms every actively registered student.</p></div><div class="divide-y divide-slate-100"><div v-for="assessment in assessments" :key="assessment.assessment_id" class="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:justify-between"><div><p class="font-semibold text-slate-900">{{ assessmentLabel(assessment) }}</p><p class="mt-1 text-xs text-slate-500">{{ assessment.course?.course_code }} — {{ assessment.course?.course_name }} · {{ assessment.course?.credit_units || 0 }} credits · {{ weight(assessment) }}%</p><p class="mt-2 text-xs" :class="assessment.published ? 'text-emerald-700' : assessment.teacher_confirmed ? 'text-amber-700' : 'text-slate-500'">{{ assessmentState(assessment) }}</p></div><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" :disabled="busy || assessment.published || !assessment.teacher_confirmed" @click="publishAssessment(assessment)">{{ assessment.published ? 'Published' : assessment.teacher_confirmed ? 'Review & Publish' : 'Awaiting Teacher Confirmation' }}</button></div><p v-if="!assessments.length" class="p-8 text-center text-sm text-slate-500">No assessment submissions were found for this term.</p></div></div>

    <div class="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h2 class="font-bold text-slate-900">Submitted mark register</h2></div><table class="min-w-[900px] w-full text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Student</th><th class="px-4 py-3">Course</th><th class="px-4 py-3">Assessment</th><th class="px-4 py-3">Mark</th><th class="px-4 py-3">Decision</th><th class="px-4 py-3">Publication</th></tr></thead><tbody><tr v-for="record in records" :key="record.record_id" class="border-b border-slate-100 last:border-0"><td class="px-4 py-3 font-semibold text-slate-900">{{ record.student?.full_name || record.student_id }}</td><td class="px-4 py-3">{{ record.assessment?.course?.course_code || '—' }}</td><td class="px-4 py-3">{{ assessmentLabel(record.assessment) }}</td><td class="px-4 py-3 font-semibold">{{ record.record_status === 'ABSENT_JUSTIFIED' ? 'Excused absence' : record.score == null ? '—' : record.score }}</td><td class="px-4 py-3">{{ record.teacher_confirmed ? 'Teacher confirmed' : 'Draft' }}</td><td class="px-4 py-3"><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="record.published ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'">{{ record.published ? 'Published' : 'Not published' }}</span></td></tr><tr v-if="!records.length"><td colspan="6" class="px-4 py-8 text-center text-slate-500">No marks are available for review.</td></tr></tbody></table></div>

    <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h2 class="font-bold text-slate-900">Final report-card publication</h2><p class="mt-1 text-xs text-slate-500">Generate the credit-weighted report card after reviewing the individual assessments, then publish it to the student and linked guardians.</p></div><label class="text-sm font-medium text-slate-700">Student<select v-model="selectedStudentId" class="mt-1 block w-72 rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Select student</option><option v-for="student in students" :key="student.student_id" :value="student.student_id">{{ student.full_name }}</option></select></label></div><div class="mt-4 flex flex-wrap gap-2"><button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 disabled:opacity-50" :disabled="busy || !selectedStudentId" @click="generateCard">Generate / review report card</button><button class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" :disabled="busy || !selectedStudentId" @click="publishCard">Publish final report card</button></div><p v-if="cardSummary" class="mt-4 rounded-lg bg-slate-50 p-4 text-sm text-slate-700">Average: <strong>{{ cardSummary.overall_average ?? '—' }}%</strong> · GPA: <strong>{{ cardSummary.gpa ?? '—' }}/4</strong> · Credits: <strong>{{ cardSummary.earned_credits }}/{{ cardSummary.total_credits }}</strong> · Status: <strong>{{ cardSummary.promotion_status }}</strong></p></div>
  </section>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { authStore } from '../store/auth'
import { fetchGradingReview, fetchStudents, publishGradingAssessment, generateReportCard, publishReportCard } from '../api.js'

const token = () => authStore.token.value
const term = ref('2026-A')
const assessments = ref([])
const records = ref([])
const students = ref([])
const selectedStudentId = ref('')
const cardSummary = ref(null)
const busy = ref(false)
const errorMessage = ref('')
const message = ref('')
const awaitingReview = computed(() => assessments.value.filter((assessment) => assessment.teacher_confirmed && !assessment.published).length)
const publishedMarks = computed(() => records.value.filter((record) => record.published).length)
function weight(assessment) { return assessment?.assessment_type === 'Final' ? 40 : assessment?.assessment_type === 'Test' ? 20 : Number(assessment?.weight || 0) }
function assessmentLabel(assessment) { return assessment?.assessment_type === 'Test' ? `Test ${assessment.assessment_number || ''}` : assessment?.assessment_type || assessment?.title || 'Assessment' }
function assessmentState(assessment) { return assessment?.published ? 'Published to student and guardian portals' : assessment?.teacher_confirmed ? 'Teacher confirmed — awaiting administrator publication' : 'Teacher has not confirmed this assessment' }
async function load() { errorMessage.value = ''; message.value = ''; const result = await fetchGradingReview(token(), { term: term.value }); if (!result.ok) { errorMessage.value = result.error; return } assessments.value = result.data?.assessments || []; records.value = result.data?.records || [] }
async function publishAssessment(assessment) { busy.value = true; errorMessage.value = ''; message.value = ''; try { const result = await publishGradingAssessment(token(), assessment.assessment_id); if (!result.ok) throw new Error(result.error); message.value = `${assessmentLabel(assessment)} published successfully.`; await load() } catch (error) { errorMessage.value = error.message || 'Unable to publish assessment.' } finally { busy.value = false } }
async function generateCard() { busy.value = true; errorMessage.value = ''; try { const result = await generateReportCard(token(), selectedStudentId.value, { term: term.value }); if (!result.ok) throw new Error(result.error); cardSummary.value = result.data?.report_card || null; message.value = 'Report card generated for administrator review.' } catch (error) { errorMessage.value = error.message || 'Unable to generate report card.' } finally { busy.value = false } }
async function publishCard() { busy.value = true; errorMessage.value = ''; try { const result = await publishReportCard(token(), selectedStudentId.value, { term: term.value }); if (!result.ok) throw new Error(result.error); cardSummary.value = result.data?.report_card || null; message.value = 'Final report card published.' } catch (error) { errorMessage.value = error.message || 'Unable to publish report card.' } finally { busy.value = false } }
onMounted(async () => { const studentsResult = await fetchStudents(token()); if (studentsResult.ok) students.value = studentsResult.data || []; await load() })
</script>
