<template>
  <div class="space-y-6">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-2xl font-bold tracking-tight text-slate-900">School Events</h1><p class="mt-1 text-xs text-slate-500">Create and publish meetings, deadlines, examinations, holidays, and institutional events.</p></div><button type="button" class="btn-primary px-3 py-2 text-xs font-semibold" :disabled="loading" @click="loadEvents">Refresh</button></div>
    <div v-if="errorMessage" class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700" role="alert">{{ errorMessage }}</div><div v-if="successMessage" class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700" role="status">{{ successMessage }}</div>
    <form class="rounded-xl border border-blue-200 bg-blue-50/60 p-5 shadow-xs" @submit.prevent="saveEvent"><h2 class="text-base font-bold text-slate-900">{{ editingId ? 'Edit school event' : 'Create school event' }}</h2><div class="mt-4 grid gap-4 md:grid-cols-4"><label class="block text-xs font-semibold text-slate-700 md:col-span-2">Title<input v-model.trim="form.title" required maxlength="200" class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal" placeholder="Faculty meeting" /></label><label class="block text-xs font-semibold text-slate-700">Category<select v-model="form.category" class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal"><option v-for="category in categories" :key="category">{{ category }}</option></select></label><label class="block text-xs font-semibold text-slate-700">Audience<select v-model="form.audience" class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal"><option v-for="audience in audiences" :key="audience">{{ audience }}</option></select></label><label class="block text-xs font-semibold text-slate-700 md:col-span-4">Description<textarea v-model.trim="form.description" required maxlength="5000" rows="2" class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal" placeholder="Explain the purpose and expected participants."></textarea></label><label class="block text-xs font-semibold text-slate-700">Start<input v-model="form.start_at" type="datetime-local" required class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal" /></label><label class="block text-xs font-semibold text-slate-700">End<input v-model="form.end_at" type="datetime-local" required class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal" /></label><label class="block text-xs font-semibold text-slate-700">Location<input v-model.trim="form.location" maxlength="255" class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal" placeholder="Main Hall" /></label><label class="block text-xs font-semibold text-slate-700">Online details<input v-model.trim="form.online_url" maxlength="500" class="mt-1.5 block w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-normal" placeholder="Optional meeting link" /></label></div><div class="mt-4 flex flex-wrap gap-2"><button type="submit" class="btn-primary px-4 py-2 text-xs font-semibold" :disabled="saving">{{ saving ? 'Saving…' : editingId ? 'Save event' : 'Save draft' }}</button><button v-if="editingId" type="button" class="btn-secondary px-4 py-2 text-xs font-semibold" @click="resetForm">Cancel</button></div></form>
    <section class="rounded-xl border border-border-subtle bg-white p-4 shadow-xs sm:p-6"><div v-if="loading" class="py-10 text-center text-sm text-slate-500">Loading events…</div><div v-else-if="!events.length" class="py-10 text-center text-sm text-slate-500">No School Events have been created.</div><div v-else class="space-y-3"><article v-for="event in events" :key="event.event_id" class="rounded-lg border border-slate-200 bg-slate-50 p-4"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold text-slate-900">{{ event.title }}</h2><span class="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-semibold text-blue-700">{{ event.status }}</span><span class="rounded-full bg-white px-2 py-1 text-[10px] font-semibold text-slate-600">{{ event.audience }}</span></div><p class="mt-1 text-xs text-slate-500">{{ event.category }} · {{ formatDate(event.start_at) }}–{{ formatDate(event.end_at) }}</p><p class="mt-2 text-sm text-slate-700">{{ event.description }}</p></div><div class="flex shrink-0 flex-wrap gap-2"><button type="button" class="btn-secondary px-2.5 py-1.5 text-xs font-semibold" @click="startEdit(event)">Edit</button><button v-if="event.status === 'Draft'" type="button" class="btn-primary px-2.5 py-1.5 text-xs font-semibold" @click="publish(event)">Publish</button><button v-if="event.status === 'Draft' || event.status === 'Published'" type="button" class="btn-danger px-2.5 py-1.5 text-xs font-semibold" @click="cancel(event)">Cancel</button><button v-if="event.status === 'Draft'" type="button" class="btn-danger px-2.5 py-1.5 text-xs font-semibold" @click="remove(event)">Delete</button></div></div></article></div></section>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { authStore } from '../store/auth.js'
import { cancelSchoolEvent, createSchoolEvent, deleteSchoolEvent, fetchSchoolEvents, publishSchoolEvent, updateSchoolEvent } from '../api.js'

const categories = ['Meeting', 'Deadline', 'Examination', 'Holiday', 'Orientation', 'Registration', 'General']
const audiences = ['Everyone', 'Teachers', 'Students', 'Guardians', 'Course', 'Class Group']
const events = ref([])
const loading = ref(true)
const saving = ref(false)
const editingId = ref('')
const errorMessage = ref('')
const successMessage = ref('')
const form = reactive({ title: '', description: '', category: 'General', audience: 'Everyone', start_at: '', end_at: '', location: '', online_url: '' })
function resetForm() { editingId.value = ''; Object.assign(form, { title: '', description: '', category: 'General', audience: 'Everyone', start_at: '', end_at: '', location: '', online_url: '' }) }
function startEdit(event) { editingId.value = event.event_id; Object.assign(form, { title: event.title, description: event.description, category: event.category, audience: event.audience, start_at: event.start_at?.slice(0, 16), end_at: event.end_at?.slice(0, 16), location: event.location || '', online_url: event.online_url || '' }); errorMessage.value = '' }
function formatDate(value) { return new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) }
async function loadEvents() { loading.value = true; errorMessage.value = ''; const result = await fetchSchoolEvents(authStore.token.value, { status: 'Draft' }); const published = await fetchSchoolEvents(authStore.token.value, { status: 'Published' }); if (!result.ok || !published.ok) errorMessage.value = result.error || published.error || 'Unable to load events.'; else events.value = [...(result.data || []), ...(published.data || [])]; loading.value = false }
async function saveEvent() { saving.value = true; errorMessage.value = ''; const body = { ...form, start_at: new Date(form.start_at).toISOString(), end_at: new Date(form.end_at).toISOString() }; const result = editingId.value ? await updateSchoolEvent(authStore.token.value, editingId.value, body) : await createSchoolEvent(authStore.token.value, body); if (!result.ok) errorMessage.value = result.error || 'Unable to save event.'; else { successMessage.value = editingId.value ? 'Event updated.' : 'Event draft created.'; resetForm(); await loadEvents() } saving.value = false }
async function publish(event) { const result = await publishSchoolEvent(authStore.token.value, event.event_id); if (!result.ok) errorMessage.value = result.error || 'Unable to publish event.'; else { successMessage.value = 'Event published.'; await loadEvents() } }
async function cancel(event) { const reason = window.prompt('Why is this event being cancelled?'); if (!reason) return; const result = await cancelSchoolEvent(authStore.token.value, event.event_id, reason); if (!result.ok) errorMessage.value = result.error || 'Unable to cancel event.'; else { successMessage.value = 'Event cancelled.'; await loadEvents() } }
async function remove(event) { if (!window.confirm(`Delete ${event.title}?`)) return; const result = await deleteSchoolEvent(authStore.token.value, event.event_id); if (!result.ok) errorMessage.value = result.error || 'Unable to delete event.'; else await loadEvents() }
onMounted(loadEvents)
</script>
